### PR TITLE
REEKOH-271

### PR DESCRIPTION
**Pull request by rozzwalla**
Storage Plugin - Couchbase Database Storage

### CODE REVIEW

**Comment by benjsicam** [comment]
Bro,

Kindly update with the latest Storage Plugin Seed code.

Thanks,

Benj

**Comment by rozzwalla** [comment]
I'm using the latest plugin storage plugin  di you push a new one?


________________________________

**Comment by rozzwalla** [comment]
Ok na naupdate na


________________________________

**Comment by benjsicam** [comment]
Bro,

Forgot to tell, we now have support for Password types sa config.json. Kindly change the type for the password param in config.json to Password instead of String.

Thanks,

Benj

**Pull request merged**
